### ISSUE TITLE
CMake Error from system install

### ISSUE THREAD

**Issue by superjax** [dpkoch/async_comm#10]
I'm trying to link against the system-installed version
`sudo apt install ros-melodic-async-comm`

with
```
find_package(catkin REQUIRED COMPONENTS
  async_comm
)
```

and I got the following error
``` bash
/home/superjax/ws/src/ublox/include/UBLOX/ublox.h:8:10: fatal error: async_comm/serial.h: No such file or directory
 #include "async_comm/serial.h"
```

Adding
`include_directories(${async_comm_INCLUDE_DIRS})`
fixed it.

**Comment by dpkoch** [comment]
`async_comm` is released through ROS as a third-party package, in accordance with the instructions [here](https://wiki.ros.org/bloom/Tutorials/ReleaseThirdParty) and with [REP 136](http://ros.org/reps/rep-0136.html). This means that it should be included as a system package, not a catkin package (so `find_package(async_comm REQUIRED)`, not `find_package(catkin REQUIRED COMPONENTS async_comm)`. The `include_directories(${async_comm_INCLUDE_DIRS})` line is required, just as for any other system package.

This is documented in the README under the `Including in your project/ROS install` section. So this is probably a non-issue? Let me know if I'm missing something.

**Comment by superjax** [comment]
Ah, I see.   Maybe I should read the instructions.  Thanks!
